NavBar Added
dscnitp/job-provider-site pull request #14
Opened 2020-10-19 17:34 UTC by Saurabhdhotre2709

Task Completed

2020-10-19 19:05 UTC, divyaprakash-Rx requested changes
@Saurabhdhotre2709 Everything works fine and nice.
Please do following, and it will be ready for merge:
- [x] The master repo is using yarn, but you are running npm for your fork. Please shift to yarn or add package-lock.json to .gitignore.
- [x] remove log files from your commits
- [ ] run 'yarn run format' to correct indentations
- [x] Please don't edit index.html file in public folder

2020-10-19 19:05 UTC, divyaprakash-Rx commented on client/public/index.html
> +/>
@Saurabhdhotre2709 Please remove cdns and use npm modules instead.

2020-10-21 19:56 UTC, Saurabhdhotre2709 commented
All require Changes have been done successfully

2020-10-22 05:49 UTC, Devanshi-123 approved these changes

2020-10-22 05:50 UTC, merged