Signup form customer (frontend)
dscnitp/job-provider-site pull request #5
Opened 2020-10-16 15:53 UTC by kunalprakash1309

Signup form customer (frontend) using semantic UI. @raksh543

2020-10-16 16:04 UTC, raksh543 commented
@kunalprakash1309 Please add screenshots for our reference

2020-10-16 16:12 UTC, kunalprakash1309 commented
Preview :- 
![Screenshot (32)](https://user-images.githubusercontent.com/42040782/96282517-7ab63680-0ff8-11eb-9d7f-ca625576bd28.png)
![Screenshot (33)](https://user-images.githubusercontent.com/42040782/96282549-830e7180-0ff8-11eb-9e09-6e8d8721e238.png)

2020-10-17 06:45 UTC, raksh543 requested changes
Please just change the background color from yellow to #f5f5f5 for now. Other changes will be notified.

2020-10-18 13:13 UTC, raksh543 approved these changes

2020-10-18 13:24 UTC, merged